// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://biompvyiogtpmakurdri.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJpb21wdnlpb2d0cG1ha3VyZHJpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njc5MDI5MjQsImV4cCI6MjA4MzQ3ODkyNH0.rMKXyMcjGs0AmR-2im_VykBSeic8us-hW3ht9ldpY7o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});